
// Homepage
const HOMEPAGE_PRODUCTS_DATA_FETCH_REQUEST = 'HOMEPAGE:PRODUCTS_DATA:FETCH:REQUEST';
const HOMEPAGE_PRODUCTS_DATA_FETCH_SUCCESS = 'HOMEPAGE:PRODUCTS_DATA:FETCH:SUCCESS';
const HOMEPAGE_PRODUCTS_DATA_FETCH_FAIL = 'HOMEPAGE:PRODUCTS_DATA:FETCH:FAIL';
const HOMEPAGE_PRODUCT_DATA_FETCH_REQUEST = 'HOMEPAGE:PRODUCT_DATA:FETCH:REQUEST';
const HOMEPAGE_PRODUCT_DATA_FETCH_SUCCESS = 'HOMEPAGE:PRODUCT_DATA:FETCH:SUCCESS';
const HOMEPAGE_PRODUCT_DATA_FETCH_FAIL = 'HOMEPAGE:PRODUCT_DATA:FETCH:FAIL';
const HOMEPAGE_CATEGORIES_DATA_FETCH_REQUEST = 'HOMEPAGE:CATEGORIES_DATA:FETCH:REQUEST';
const HOMEPAGE_CATEGORIES_DATA_FETCH_SUCCESS = 'HOMEPAGE:CATEGORIES_DATA:FETCH:SUCCESS';
const HOMEPAGE_CATEGORIES_DATA_FETCH_FAIL = 'HOMEPAGE:CATEGORIES_DATA:FETCH:FAIL';
const HOMEPAGE_PRODUCTS_DATA_SEARCH = 'HOMEPAGE:PRODUCTS_DATA:SEARCH';
const HOMEPAGE_PRODUCTS_DATA_FILTER = 'HOMEPAGE:PRODUCTS_DATA:FILTER';
const HOMEPAGE_PRODUCTS_DATA_FILTER_PRICE = 'HOMEPAGE:PRODUCTS_DATA:FILTER_PRICE';
const HOMEPAGE_PRODUCTS_DATA_FILTER_RATING = 'HOMEPAGE:PRODUCTS_DATA:FILTER_RATING';
const HOMEPAGE_PRODUCTS_DATA_FILTER_GENDER = 'HOMEPAGE:PRODUCTS_DATA:FILTER_GENDER';

// Createpage
const CREATEPAGE_PRODUCTS_DATA_SUBMIT_REQUEST = 'CREATEPAGE:PRODUCTS_DATA:SUBMIT:REQUEST';
const CREATEPAGE_PRODUCTS_DATA_SUBMIT_SUCCESS = 'CREATEPAGE:PRODUCTS_DATA:SUBMIT:SUCCESS';
const CREATEPAGE_PRODUCTS_DATA_SUBMIT_FAIL = 'CREATEPAGE:PRODUCTS_DATA:SUBMIT:FAIL';

// View Product
const VIEW_PAGE_ADD_TO_CART = 'VIEW_PAGE:ADD_PRODUCT:TO:CART';
const VIEW_PAGE_ADD_TO_FAVOURITE = 'VIEW_PAGE:ADD_PRODUCT:TO:FAVOURITE';
const VIEW_PAGE_REMOVE_ITEM = 'VIEW_PAGE_REMOVE_ITEM';
const VIEW_PAGE_CLEAR_CART = 'VIEW_PAGE_CLEAR_CART';
const VIEW_PAGE_REMOVE_ITEM_FAVOURITE = 'VIEW_PAGE_REMOVE_ITEM_FAVOURITE';
const VIEW_PAGE_CHANGE_ITEM_QTY = 'VIEW_PAGE_CHANGE_ITEM_QTY';

// Checkout page
const CHECKOUTPAGE_ORDER_DATA_SUBMIT_REQUEST = 'CHECKOUTPAGE:ORDER:SUBMIT:REQUEST';
const CHECKOUTPAGE_ORDER_DATA_SUBMIT_SUCCESS = 'CHECKOUTPAGE:ORDER:SUBMIT:SUCCESS';
const CHECKOUTPAGE_ORDER_DATA_SUBMIT_FAIL = 'CHECKOUTPAGE:ORDER:SUBMIT:FAIL';
const CHECKOUTPAGE_CLEAR_ORDER_DATA = 'CHECKOUTPAGE:CLEAR_ORDER:DATA';

// Orders
const ORDERS_PAGE_ORDERS_DATA_FETCH_REQUEST = 'ORDERS_PAGE:ORDERS_DATA:FETCH:REQUEST';
const ORDERS_PAGE_ORDERS_DATA_FETCH_SUCCESS = 'ORDERS_PAGE:ORDERS_DATA:FETCH:SUCCESS';
const ORDERS_PAGE_ORDERS_DATA_FETCH_FAIL = 'ORDERS_PAGE:ORDERS_DATA:FETCH:FAIL';

export {
  HOMEPAGE_PRODUCTS_DATA_FETCH_REQUEST,
  HOMEPAGE_PRODUCTS_DATA_FETCH_SUCCESS,
  HOMEPAGE_PRODUCTS_DATA_FETCH_FAIL,
  HOMEPAGE_CATEGORIES_DATA_FETCH_REQUEST,
  HOMEPAGE_CATEGORIES_DATA_FETCH_SUCCESS,
  HOMEPAGE_CATEGORIES_DATA_FETCH_FAIL,
  HOMEPAGE_PRODUCTS_DATA_SEARCH,
  HOMEPAGE_PRODUCTS_DATA_FILTER,
  HOMEPAGE_PRODUCTS_DATA_FILTER_PRICE,
  HOMEPAGE_PRODUCT_DATA_FETCH_REQUEST,
  HOMEPAGE_PRODUCT_DATA_FETCH_SUCCESS,
  HOMEPAGE_PRODUCT_DATA_FETCH_FAIL,
  HOMEPAGE_PRODUCTS_DATA_FILTER_RATING,
  CREATEPAGE_PRODUCTS_DATA_SUBMIT_REQUEST,
  CREATEPAGE_PRODUCTS_DATA_SUBMIT_SUCCESS,
  CREATEPAGE_PRODUCTS_DATA_SUBMIT_FAIL,
  HOMEPAGE_PRODUCTS_DATA_FILTER_GENDER,
  VIEW_PAGE_ADD_TO_CART,
  VIEW_PAGE_ADD_TO_FAVOURITE,
  VIEW_PAGE_REMOVE_ITEM,
  VIEW_PAGE_CHANGE_ITEM_QTY,
  VIEW_PAGE_REMOVE_ITEM_FAVOURITE,
  VIEW_PAGE_CLEAR_CART,
  CHECKOUTPAGE_ORDER_DATA_SUBMIT_REQUEST,
  CHECKOUTPAGE_ORDER_DATA_SUBMIT_SUCCESS,
  CHECKOUTPAGE_ORDER_DATA_SUBMIT_FAIL,
  CHECKOUTPAGE_CLEAR_ORDER_DATA,
  ORDERS_PAGE_ORDERS_DATA_FETCH_REQUEST,
 ORDERS_PAGE_ORDERS_DATA_FETCH_SUCCESS,
 ORDERS_PAGE_ORDERS_DATA_FETCH_FAIL
};
